{
 "title": "devops-cluster",
 "time": { "from": "2025-11-24T11:47:24.640Z", "to": "2025-11-24T13:48:06.216Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Ping Service - Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pong_http_requests_total[1m])) by (path, status, method)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Ping Service - Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ping_http_requests_total[1m])) by (path, status, method)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Pong Service - Requests Per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, path, status) (rate(pong_http_requests_total{namespace=\"test\"}[1m]))\r\n",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Ping Service - Requests Per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, path, status) (rate(ping_http_requests_total{namespace=\"test\"}[1m]))",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Pong Service - Dependency Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(pong_dependency_duration_seconds_bucket{target_service=\"ping-service\"}[5m])) by (target_service,method)",
     "legendFormat": "{{target_service}} {{method}}"
    }
   ]
  },
  {
   "title": "Ping Service - Dependency Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(ping_app_dependency_duration_seconds_bucket{target_service=\"pong-service\"}[5m])) by (target_service, method)",
     "legendFormat": "{{target_service}} {{method}}"
    }
   ]
  },
  {
   "title": "Pong Service - Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pong_http_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping service - Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ping_http_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "{{le}} {{path}}"
    }
   ]
  },
  {
   "title": "Pong Service - Traffic Loop Latency Dashboard",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ping_http_request_duration_seconds_sum[1m])) by (path) \r\n/ \r\nsum(rate(ping_http_request_duration_seconds_count[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Ping Service - Traffic Loop Latency Dashboard",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ping_http_request_duration_seconds_sum[1m])) by (path) \r\n/ \r\nsum(rate(ping_http_request_duration_seconds_count[1m])) by (path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Services - Saturation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ping_http_requests_in_flight) by (method, path) + sum(pong_http_requests_in_flight) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Request For 1 Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 48 },
   "targets": [
    {
     "expr": "round(sum(increase(http_requests_total{namespace=\"test\"}[1m])) by (path, method))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}